# Example

In [2]:
import numpy as np

In [3]:
np.empty(4)

array([4.64531993e-310, 0.00000000e+000, 4.64592360e-310, 4.64592361e-310])

In [4]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
x[0:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

In [6]:
x = np.arange(10)
y = x[2:5]

In [7]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [10]:
x = np.arange(6)

In [11]:
x

array([0, 1, 2, 3, 4, 5])

In [12]:
y = x.reshape((2,3))

In [13]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
x

array([0, 1, 2, 3, 4, 5])

In [15]:
z = x
z.shape = (3,2)

In [16]:
z

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
y

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
y[0,0] = -1

In [20]:
y

array([[-1,  1,  2],
       [ 3,  4,  5]])

In [21]:
z

array([[-1,  1],
       [ 2,  3],
       [ 4,  5]])

In [23]:
y[1,2] = -2

In [24]:
y

array([[-1,  1,  2],
       [ 3,  4, -2]])

In [25]:
z

array([[-1,  1],
       [ 2,  3],
       [ 4, -2]])

In [28]:
y = np.ones(
  (2,2)
)

In [29]:
y

array([[1., 1.],
       [1., 1.]])

In [32]:
y.resize((3,3), refcheck=False)

In [33]:
y

array([[1., 1., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

In [34]:
sum(np.arange(1000))

499500

# Regression example

In [35]:
rng = np.random.default_rng(seed=12345)
n = 1000

In [49]:
## Create data
X = np.hstack(
  [ np.ones((n,1)),
    rng.random((n,5))]
)

beta = np.array([3.5,1.8,-7.5,0, 3, 9.8]).reshape((-1,1))
err = rng.normal(0, 0.1, (n,1))

y = X @ beta + err

In [51]:
y.shape

(1000, 1)

In [55]:
## Fit model

np.round(np.linalg.inv(X.T @ X) @ X.T @ y,2).T

array([[ 3.51,  1.8 , -7.5 , -0.01,  2.98,  9.8 ]])

In [57]:
[
    (np.linalg.inv(X[:s,:].T @ X[:s,:]) @ X[:s,:].T @ y[:s,:]).T  for s in [10,100,250,500,1000]
]

[array([[ 3.65866294,  1.79828338, -7.48834711, -0.12248825,  3.04190149,
          9.50057453]]),
 array([[ 3.57449143,  1.79734447, -7.49000566, -0.11556864,  2.99614371,
          9.74479266]]),
 array([[ 3.52442606,  1.76689235, -7.4787416 , -0.05976485,  3.03190601,
          9.79133471]]),
 array([[ 3.51735662,  1.78314812, -7.48943429, -0.02726953,  3.00566035,
          9.78373101]]),
 array([[ 3.51283086e+00,  1.79567488e+00, -7.50001036e+00,
         -8.75862646e-03,  2.98471038e+00,  9.79544126e+00]])]