## Setup

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

import torch

## Exercise 1

In [20]:
a = torch.rand(4, 3, 2)
b = torch.rand(   3, 2)
c = torch.rand(   2, 3)
d = torch.rand(0) 
e = torch.rand(   3, 1)
f = torch.rand(   1, 2)

In [24]:
d

tensor([])

In [27]:
(a * f).shape

torch.Size([4, 3, 2])

## Exercise 2

In [28]:
a = torch.ones(4,3,2)
b = torch.rand(    3)
c = torch.rand(  5,3)

In [31]:
(a * b.unsqueeze(1)).shape

torch.Size([4, 3, 2])

In [33]:
(c.unsqueeze(2)).shape

torch.Size([5, 3, 1])

In [35]:
(a.unsqueeze(1)).shape

torch.Size([4, 1, 3, 2])

In [37]:
(a.unsqueeze(1) * c.unsqueeze(2)).shape

torch.Size([4, 5, 3, 2])

In [38]:
(a * c.unsqueeze(2).unsqueeze(1)).shape

torch.Size([5, 4, 3, 2])

## Demo

In [40]:
def f(x, y):
  return 3*x + 1 + 2*y**2 + x*y

In [41]:
for x in [0.,1.]:
  for y in [0.,1.]:
    print("x =",x, "y = ",y)
    inputs = (torch.tensor([x]), torch.tensor([y]))
    print(torch.autograd.functional.jacobian(f, inputs),"\n")

x = 0.0 y =  0.0
(tensor([[3.]]), tensor([[0.]])) 

x = 0.0 y =  1.0
(tensor([[4.]]), tensor([[4.]])) 

x = 1.0 y =  0.0
(tensor([[3.]]), tensor([[1.]])) 

x = 1.0 y =  1.0
(tensor([[4.]]), tensor([[5.]])) 

