In [3]:
import numpy as np

## Exercise 1

Write an expression to obtain the center 2x2 values (i.e. 5, 6, 9, 10 as a matrix).

In [4]:
x = np.arange(16).reshape((4,4)); x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
x[(1,2),(1,2)]

array([ 5, 10])

In [13]:
x[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [14]:
x[(1,2),:][:, (1,2)]

array([[ 5,  6],
       [ 9, 10]])

## Exercise 2

We will now use this to attempt a simple brute force approach to numerical optimization, define a grid of points using `meshgrid()` to approximate the minima the following function:

$$f(x,y)=(1−x)^2+100(y−x^2)^2$$

Considering values of $x,y \in (−1,3)$, which value(s) of $x,y$ minimize this function?

In [29]:
pts = np.linspace(-1, 3, 10000)
x, y = np.meshgrid(pts, pts)

In [30]:
f = (1-x)**2 + 100*(y - x**2)**2

In [31]:
min = np.min(f)

(x[f == min],
 y[f == min])


(array([1.00020002]), array([1.00060006]))

In [32]:
min_i = np.argmin(f,axis=None)

In [33]:
( x.reshape(-1)[min_i],
  y.reshape(-1)[min_i])

(1.0002000200020005, 1.0006000600060005)

## Exercise 3

For each of the following combinations determine what the resulting dimension will be using broadcasting

* A [128 x 128 x 3] + B [3]

```
A     128 x 128 x 3
B                 3
-------------------
A + B 128 x 128 x 3
```

* A [8 x 1 x 6 x 1] + B [7 x 1 x 5]

```
A     8 x 1 x 6 x 1
B         7 x 1 x 5
-------------------
A + B 8 x 7 x 6 x 5
```

* A [2 x 1] + B [8 x 4 x 3]

```
A             2 x 1
B         8 x 4 x 3
-------------------
A + B         X x 3 -> Error
```

* A [3 x 1] + B [15 x 3 x 5]

```
A             3 x 1
B        15 x 3 x 5
-------------------
A + B    15 x 3 x 5   
```

* A [3] + B [4]

```
A            3
B            4
--------------
A + B        X -> Error
```

## Demo 1

In [34]:
rng = np.random.default_rng(1234)
d = rng.normal(loc=[-1,0,1], scale=[1,2,3], size=(1000,3))

In [35]:
d

array([[-2.60383681,  0.12819983,  3.22267389],
       [-0.84738081,  1.72748778,  9.73929767],
       [-2.47882336,  1.89094595, -3.99840637],
       ...,
       [-0.70173602, -1.00685694,  4.73479258],
       [-2.53070737, -1.61987846, -3.09503767],
       [ 0.20192215, -1.36334125, -1.24706282]])

In [36]:
d.mean(axis=0)

array([-1.0294382 , -0.01396257,  1.01241784])

In [39]:
d.std(axis=0)

array([0.99674719, 2.03222595, 3.10625219])

In [40]:
d_norm = (d - d.mean(axis=0))/d.std(axis=0) 

In [42]:
d_norm.shape

(1000, 3)

In [44]:
( d_norm.mean(axis=0),
  d_norm.std(axis=0) )

(array([ 2.35367281e-17,  7.32747196e-18, -1.79078974e-16]),
 array([1., 1., 1.]))